apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-client
  template:
    metadata:
      labels:
        app: chat-client
    spec:
      containers:
        - name: chat-client
          image: your-dockerhub-user/chat-client:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: chat-config
            - secretRef:
                name: chat-secrets
