apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
spec:
  replicas: 2  # Başlangıç için 2 replika
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
        - name: chat-server
          image: your-dockerhub-user/chat-server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chat-config
            - secretRef:
                name: chat-secrets
