FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o client client.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/client .

CMD ["/app/client"]	
