FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o server server.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server . 

CMD ["/app/server"]

